# Generated by Django 6.0.1 on 2026-01-25 23:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entradas (Dinheiro)'), ('CARTAO', 'Vendas Cartão/Pix'), ('SAIDA', 'Saídas/Despesas')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_final_fisico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loja_fechada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DINHEIRO', 'Entrada Dinheiro'), ('CARTAO', 'Cartão/Pix'), ('SAIDA', 'Saída do Caixa'), ('REGISTRO', 'Registro')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição (Opcional)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoria')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='financeiro.fechamentocaixa')),
            ],
        ),
    ]
