# Generated by Django 6.0.1 on 2026-01-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('CARTAO', 'Vendas no Cartão/Pix'), ('DINHEIRO', 'Entrada em Dinheiro'), ('SAIDA', 'Saídas em Dinheiro')], default='CARTAO', max_length=10),
        ),
    ]
