# Generated by Django 6.0.1 on 2026-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='loja_fechada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='nome',
            field=models.CharField(default='Transação', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('DINHEIRO', 'Entrada Dinheiro'), ('CARTAO', 'Cartão/Pix'), ('SAIDA', 'Saída/Sangria')], max_length=10),
        ),
    ]
