# Generated by Django 6.0.1 on 2026-01-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('DINHEIRO', 'Entrada Dinheiro'), ('CARTAO', 'Cartão/Pix'), ('SAIDA', 'Saída do Caixa'), ('REGISTRO', 'Registro')], db_index=True, max_length=10),
        ),
    ]
