# Generated by Django 6.0.1 on 2026-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_movimentacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='cache_total_cartao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='cache_total_saida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
