# Generated by Django 6.0.1 on 2026-01-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_remove_fechamentocaixa_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='saldo_final_fisico',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
