# Generated by Django 6.0.1 on 2026-01-30 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_fechamentocaixa_cache_total_cartao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechamentocaixa',
            old_name='saldo_final_fisico',
            new_name='saldo_final',
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='loja_fechada',
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='cache_total_suprimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('CARTAO', 'Cartão/Pix')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='data',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoria'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('DINHEIRO', 'Entrada Dinheiro'), ('CARTAO', 'Cartão/Pix'), ('SAIDA', 'Saída'), ('REGISTRO', 'Registro')], db_index=True, default='SAIDA', max_length=20),
        ),
    ]
