# Generated by Django 6.0.1 on 2026-01-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_fechamentocaixa_saldo_final_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='saldo_final_fisico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
