# Generated by Django 6.0.1 on 2026-01-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_fechamentocaixa_saldo_final_fisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('DINHEIRO', 'Entrada Dinheiro'), ('CARTAO', 'Cartão/Pix'), ('SAIDA', 'Saída do Caixa'), ('REGISTRO', 'Registro')], max_length=10),
        ),
    ]
